"""empty message

Revision ID: 05422240d527
Revises: 2d9f91b73957
Create Date: 2020-04-09 20:47:15.529419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05422240d527'
down_revision = '2d9f91b73957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mask', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mask')
    # ### end Alembic commands ###
